name: null
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pandas
  - pip
  - numpy
  - pip:
    - albumentations
    - flask~=1.1.1
    - google-cloud-storage
    - requests
    - tensorflow-gpu==2.0.*