name: app-env
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - imageio
  - python=3.6
  - pandas
  - pillow
  - pip
  - numpy
  - scikit-learn
  - pip:
    - google-cloud-storage
    - requests
    - rasterio